export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';

export const GET_BUILDS = 'GET_BUILDS';
export const GET_BUILDS_SUCCESS = 'GET_BUILDS_SUCCESS';

export const REQUEST_BUILD = 'REQUEST_BUILD';
export const REQUEST_BUILD_SUCCESS = 'REQUEST_BUILD_SUCCESS';

export const GET_BUILD = 'GET_BUILD';
export const GET_BUILD_SUCCESS = 'GET_BUILD_SUCCESS';

export const GET_BUILD_LOGS = 'GET_BUILD_LOGS';
export const GET_BUILD_LOGS_SUCCESS = 'GET_BUILD_LOGS_SUCCESS';
